### ISSUE TITLE
Multiple Mapping Columns

### ISSUE THREAD

**Issue by scottwater** [wittydeveloper/attr_bitwise#10] opened 2016-04-28 17:29 UTC
Any thoughts to supporting more than one column per model? 

By a quick look, if the column name were passed to add_value, remove_value, etc it looks like multiple columns might work. 

-Scott

**Comment by charlypoly** [comment] 2016-04-29 07:26
Hi Scoot,

I think that multiple column is already supported ;) 

For example with this configuration : 

``` ruby
class User < ActiveRecord::Base
  include AttrBitwise

  attr_bitwise :locales, mapping: [:en, :fr, :de]

  attr_bitwise :country, mapping: [:france, :italy]

end

user = User.new

user.add_locale :fr
user.add_country :france

user.countries # => [:france]
user.locales # => [:fr]

```

Is that what you need ? 

_But, note that it's not possible to do AND and OR operations between two columns since theses columns will use same values._

**Comment by scottwater** [comment] 2016-04-29 14:15
In my tests, the values are always saved on the second defined column.

My goal is to keep the two columns completely isolated from each other.  So
I guess to be more clear, I am trying to add two attr_bitwise definitions
to a model and store each in its own column.

Is that supported? If so maybe I messed up the configuration.

Thanks
Scott

On Friday, April 29, 2016, Charly POLY notifications@github.com wrote:

> Hi Scoot,
> 
> I think that multiple column is already supported ;)
> 
> For example with this configuration :
> 
> class User < ActiveRecord::Base
>   include AttrBitwise
> 
>   attr_bitwise :locales, mapping: [:en, :fr, :de]
> 
>   attr_bitwise :country, mapping: [:france, :italy]
> end
> 
> user = User.new
> 
> user.add_locale :fr
> user.add_country :france
> 
> user.countries # => [:france]
> user.locales # => [:fr]
> 
> Is that what you need ?
> 
> _But, note that it's not possible to do AND and OR operations between two
> columns since theses columns will use same values._
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/wittydeveloper/attr_bitwise/issues/10#issuecomment-215646520

## 

Scott Watermasysk
http://scottw.com
http://twitter.com/scottw

**Comment by scottwater** [comment] 2016-05-02 16:06
Just to follow up, updating the spec test class like this causes four failures. 

``` ruby
  class TestClass

    include AttrBitwise

    attr_accessor :fruits_value
    attr_accessor :vegatable_value

    attr_bitwise :fruits, mapping: [:banana, :apple]
    attr_bitwise :vegatable, mapping: [:carrot, :pepper]

    def initialize
      @fruits_value = 0
      @vegatable_value = 0
    end

  end

```

Any thing else need to be explicitly configured to make this work?

**Comment by blid** [comment] 2016-05-02 21:03
@scottwater: I confirmed your issue. It was because dynamic methods `value` and `value=` were set to last defined `attr_bitwise` in `TestClass`. 

I'm working on proper fix for this issue.

**Closed as completed** 2016-05-03 07:45 UTC
